categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
  - title: "⬆️ Dependencies"
    labels:
      - "dependencies"
change-title-escapes: '\<*_&`'
commitish: main

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
    branch:
      - '/docs{0,1}\/.+/'
  - label: "bugfix"
    branch:
      - '/bugfix\/.+/'
    title:
      - "/fix/i"
  - label: "feature"
    branch:
      - '/feature\/.+/'
    title:
      - "/refactor/i"
      - "/add/i"
  - label: "dependencies"
    branch:
      - '/dependabot\/.+/'

template: |
  ## What's Changed

  $CHANGES
