[tool.black]
line-length = 88
target-version = ["py39", "py310", "py311", "py312", "py313"]
exclude = '''

(
  /(
      \.eggs
    | \.git
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
)
'''
