blank_issues_enabled: false
contact_links:
  - name: Questions & help
    url: https://github.com/timlaing/pyicloud/discussions
    about: Ask questions and get help from maintainers and the community.
