# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: versioned_document.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 31, 1, "", "versioned_document.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x18versioned_document.proto\x12\x12versioned_document"V\n\x08\x44ocument\x12\x1c\n\x14serializationVersion\x18\x01 \x01(\r\x12,\n\x07version\x18\x02 \x03(\x0b\x32\x1b.versioned_document.Version"V\n\x07Version\x12\x1c\n\x14serializationVersion\x18\x01 \x01(\r\x12\x1f\n\x17minimumSupportedVersion\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "versioned_document_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_DOCUMENT"]._serialized_start = 48
    _globals["_DOCUMENT"]._serialized_end = 134
    _globals["_VERSION"]._serialized_start = 136
    _globals["_VERSION"]._serialized_end = 222
# @@protoc_insertion_point(module_scope)
